[workspace]
resolver = "2"

members = [
    "code/guide/getting-started/*"
]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[workspace.dependencies]
winit = "0.30"
pollster = "0.4"
tokio = { version = "1.43", features = ["parking_lot", "rt"] }
tracing = "0.1"
tracing-subscriber = "0.3"
wgpu = "24.0"
image = "0.25"
glam = { version = "0.29", features = ["debug-glam-assert"] }
encase = { version = "0.10", features = ["glam"] }
