[workspace]
resolver = "2"

members = [
    "code/guide/getting-started/*"
]

[workspace.package]
version = "0.1.0"
authors = ["Bromles <bromles@yandex.ru>"]
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[profile.release]
lto = true
codegen-units = 1
opt-level = 3

[workspace.dependencies]
#region deps
winit = "0.30"
tokio = { version = "1.45", features = ["parking_lot", "rt"] }
tracing = "0.1"
tracing-subscriber = "0.3"
bytemuck = { version = "1.23", features = ["derive"] }
wgpu = "25.0"
image = "0.25"
glam = { version = "0.30", features = ["debug-glam-assert"] }
encase = { version = "0.11", features = ["glam"] }
#endregion deps
