[package]
name = "creating-window"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
winit.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
log = "0.4.22"
