[package]
name = "hello-triangle"
version = "0.1.0"
edition = "2021"

[dependencies]
winit.workspace = true
pollster.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true
