[package]
name = "hello-triangle"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
winit.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true
