[package]
name = "init-wgpu"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
winit.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wgpu.workspace = true
